# Generated by Django 2.2 on 2019-05-01 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TypeDocument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('abreviation', models.CharField(blank=True, max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.CharField(max_length=20)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino')], default='M', max_length=2)),
                ('birthdate', models.DateField(verbose_name='Fecha Nacimiento')),
                ('grade', models.IntegerField()),
                ('group', models.IntegerField()),
                ('estract', models.IntegerField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('document_type', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='students.TypeDocument')),
                ('institution', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.Institution')),
            ],
        ),
    ]
