# Generated by Django 2.2 on 2019-05-01 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_auto_20190501_1551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.CharField(max_length=50),
        ),
    ]
