# Generated by Django 2.2 on 2019-05-01 16:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_auto_20190501_1614'),
    ]

    operations = [
        migrations.CreateModel(
            name='DactilarIdentification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dactilar_md', models.BinaryField()),
                ('dactilar_mi', models.BinaryField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='students.Student')),
            ],
        ),
    ]
