# Generated by Django 2.2 on 2019-05-01 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_dactilaridentification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='estract',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
