# Generated by Django 2.2 on 2019-05-02 02:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_auto_20190501_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='dactilaridentification',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dactilaridentification',
            name='modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='document',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
